#!/usr/bin/env node

require('peer-star-app/bin/pinner')

// From: https://nodejs.org/en/docs/guides/getting-started-guide/
// Just to keep Zeit now from complaining

const http = require('http')

const hostname = '127.0.0.1'
const port = 3010

const server = http.createServer((req, res) => {
  res.statusCode = 200
  res.setHeader('Content-Type', 'text/plain')
  res.end('Hello World\n')
});

server.listen(port, hostname, () => {
  console.log(`Server running at http://${hostname}:${port}/`)
})
